# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_img',
            field=models.ImageField(upload_to='posts'),
        ),
    ]
