# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_on',
            field=models.DateTimeField(null=True),
        ),
    ]
